inseven/fileaway

FileActions.xcworkspace/contents.xcworkspacedata, scripts/build.sh
It looks like an absolute path found its way into the FileActions workspace meaning that builds wouldn't work unless the source was checked out in a very specific location. This fixes that and adds the FileActions workspace to the GitHub actions builds.
=> Fix a build issue in the legacy FileActions workspace and enable iOS builds

macos/Fileaway-macOS.xcodeproj/project.pbxproj, macos/Fileaway/Modifiers/Toolbar.swift
In order to use SearchField in other projects, it needs to be moved into the Interact Swift package.
=> Move SearchField into Interact

README.md, macos/Fileaway/FileawayApp.swift
This requires an update to the Interact package to pick up the new window frame autosaving functionality.
=> Save the main window frame

macos/Fileaway/Views/Settings/RulesSettingsView.swift
The tap handler which was trying to add double-click support to open rules in settings made it impossible to select rules if you clicked on the text, and impossible to double-click to open if you clicked anywhere other than the text. 🥴
=> fix: Make double-clicking to open rules in settings more reliable

.github/workflows/build.yaml, scripts/build.sh, scripts/release.sh
This change makes use of the new functionality in 'changes' to run the GitHub cli and create a release based on the newly created version tag.
It includes a drive-by fix to add a flag to the build script to skip notarisation for local builds (`--skip-notarize`), and changes the packaging structure slightly to match better the release needs.
=> ci: Introduce a dedicated script to add a version tag and GitHub release

macos/Fileaway/Views/QuickLookPreview.swift
It looks a lot like the SwiftUI-QLPreviewView interaction has changed in a recent release that means the QLPreviewView close is now occuring at the wrong time, leading to a crash. This workaround may introduce a memory leak (see https://github.com/jbmorley/fileaway/issues/100).
=> fix: Fixed a crash when closing the Rules Wizard

scripts/build.sh, scripts/release.sh
This change also moves the actual release operation out to a separate script to make it easier to improve logging when running the GitHub cli.
=> ci(macOS): Upload the release files separately to work around a GitHub bug

.github/workflows/build.yaml
I was previously using a personal token, which seems an unnecessary leak of my private account and is misleading if others ever make changes that trigger a release.
=> ci(macOS): Use the built-in GitHub token for releases

macos/Fileaway/Views/Settings/DestinationList.swift
This change also tweaks the layout of the rule editing buttons a little. Fix for https://github.com/jbmorley/fileaway/issues/115.
=> feat(macOS): Add a button to add text to rules

.gitmodules, scripts/build.sh
There’s no need for this to clutter the top-level directory.
=> ci(macOS): Move changes dependency into the scripts folder

.gitmodules, scripts/build.sh
Notarized apps can become invalid if they’re compressed in a way that follows symlinks. This change ensures that the zip preserves the symlinks and adds a belt-and-braces check to ensure the resulting zip is still notarized.
See https://github.com/jbmorley/fileaway/issues/120.
=> ci(macOS): Preserve symlinks in the app zip and verify the output

macos/Fileaway-macOS.xcodeproj/project.pbxproj, macos/Fileaway/Views/MenuItem.swift, macos/Fileaway/Views/Settings/RulesEditor.swift, macos/Fileaway/Views/Settings/RulesSettingsView.swift
This change introduces a new SwiftUI View, `MenuItem` that correctly determines the items that the current context menu should act upon. This is necessary as the loop item in the `ForEach` isn't actually the focused item--macOS uses the loop item _if_ there is no existing selection or the loop item is outside the current selection, or the selected items if the loop item / right click item is within the selection.
=> fix(macOS): Duplicate and delete context menu items act on all selected rules in the Rules editor

macos/Fileaway/Views/Settings/DestinationList.swift
The directory picker in the Rules editor didn’t have a default location, meaning it opened in the last directory the user had used. This is confusing and makes it really easy to mistakenly pick a directory that’s not contained within the archive root. This change uses the existing directory if it exists, and the root of the archive otherwise.
=> fix(macOS): Set the initial directory when picking rules destinations

core/FileawayCore.xcodeproj/project.pbxproj, core/FileawayCore/DateFinder.swift, core/FileawayCore/DateInstance.swift, core/FileawayCore/FileInfo.swift, core/FileawayCore/TitleFinder.swift, core/FileawayCoreTests/DateFinderTests.swift, core/FileawayCoreTests/TitleFinderTests.swift
This change only strips dates from the beginning of filenames to try to prevent the title from becoming confusing when elements are missing. It also introduces new, more permissive, date detection (using NSDataDetector) which will hopefully prove a positive experience. Longer term, it’s quite possible that users may prefer more explicit control over the date formats that are recognised (e.g., always recognise ISO dates vs US dates, etc), but this can be added later if required.
=> fix: Only strip dates at the beginning of filenames

core/FileawayCore.xcodeproj/project.pbxproj, core/FileawayCoreTests/Extensions/URL.swift, macos/Fileaway/Utilities/DirectoryObserver.swift, macos/Fileaway/Views/Wizard/TaskPage.swift
I was incorrectly using `lastPathComponent` as the display name for directories and files, even though `FileManager` has an explicit `displayName` which should be used for this.
=> fix: Correct display name for iCloud Drive and other special directories

core/FileawayCore.xcodeproj/project.pbxproj, core/FileawayCore/DateFinder.swift, core/FileawayCore/DateType.swift, core/FileawayCore/FileDate.swift, core/FileawayCore/FileInfo.swift, macos/Fileaway/Utilities/DirectoryObserver.swift, macos/Fileaway/Views/DateView.swift
This change also moves caching into the DirectoryObserver and out of the DateFinder and TitleFinder utilities to better match the lifecycle of the data and sure up thread safety.
In order to better help users understand where the dates are coming from, it adds a tooltip to the date element in the list.
=> feat: Sort by the file creation date if no date can be found in the filename

README.md
This change includes a drive-by fix to correct the release link, and the application name in the licesne section of the README.
=> docs: Document the TRY_RELEASE environment variable

README.md, scripts/build.sh
Previously, even though it was ignored, the `TRY_RELEASE` environment variable needed to be defined as otherwise it caused an unbound variable error.
=> ci: Ensure TRY_RELEASE doesn't need to be defined for local builds

.github/workflows/build.yaml
Since the Big Sur self-hosted runner builds npow seem reliable, it's OK to disable the GitHub Catalina builds.
=> ci: Disable GitHub Catalina builds

macos/Fileaway/Core/RuleState.swift, macos/Fileaway/Views/Settings/VariableList.swift
It often makes sense to fill variables in in a specific order. This change allows them to be reordered in the rule editor.
=> feat: Reorder rule variables

macos/Fileaway/Views/PageLink.swift, macos/Fileaway/Views/Wizard/TaskPage.swift
If the search string results in a single matching rule, hitting the enter key will select the rule.
=> feat: Hit enter to select the matching rule in the Rules Wizard

macos/Fileaway/FileawayApp.swift, macos/Fileaway/Modifiers/Toolbar.swift, macos/Fileaway/Utilities/SelectionManager.swift, macos/Fileaway/Views/DirectoryView.swift, macos/Fileaway/Views/FileRow.swift
This change temporarily removes the icons as the current implementation performs poorly now we're using `List`. It also makes no attempt to clean up the layout issues resulting from the update to target macOS Ventura.
=> fix: Update to the new SwiftUI list multi-selection support

macos/Fileaway/FileawayApp.swift, macos/Fileaway/Modifiers/Toolbar.swift, macos/Fileaway/Views/DirectoryView.swift, macos/Fileaway/Views/Wizard/RulesWizard.swift
This fixes the bug where the wizard might open in the wrong version of Fileaway if multiple development copies were installed.
=> fix: Use the new SwiftUI mechanism for opening new windows

core/Sources/FileawayCore/Model/SelectionModel.swift, macos/Fileaway-macOS.xcodeproj/project.pbxproj, macos/Fileaway/Extensions/UserDefaults.swift, macos/Fileaway/Views/Wizard/DetailsPage.swift, macos/Fileaway/Views/Wizard/TaskPage.swift, macos/Fileaway/Views/Wizard/TaskPageModel.swift
This also includes drive-by fixes to move the `UserDefaults` extension into a separate file and remove some commented out code.
=> refactor: Move `TaskPageModel` into a separate file

core/Sources/FileawayCore/Configuration/Rule.swift, core/Sources/FileawayCore/Configuration/RuleList.swift, core/Sources/FileawayCore/Configuration/Task.swift, core/Sources/FileawayCore/Manager.swift, core/Sources/FileawayCore/Model/RulesModel.swift, core/Sources/FileawayCore/Model/TaskModel.swift, ios/Fileaway/Settings.swift, ios/Fileaway/View Controllers/PickerViewController.swift
This also includes a drive-by refactor to reanem `Configuration` and `ConfigurationList` to `Rule` and `RuleList`.
=> fix: Ensure the iOS app stores rules in the correct format

core/Sources/FileawayCore/Views/DateView.swift, core/Sources/FileawayCore/Views/DirectoryView.swift, core/Sources/FileawayCore/Views/FileRow.swift, macos/Fileaway-macOS.xcodeproj/project.pbxproj
This change moves `DateView`. `DirectoryView`, and `FileRow` into FileawayCore to allow them to be reused in the iOS app.
=> refactor: Move macOS views into FileawayCore

core/Sources/FileawayCore/Model/SceneModel.swift
This change includes a drive-by-fix to avoid unnecessary work indexing the directories.
=> fix: Open the first inbox by default

core/Sources/FileawayCore/Model/ApplicationModel.swift, core/Sources/FileawayCore/Utilities/DirectoryMonitor.swift, core/Sources/FileawayCore/Views/Viewer/LocationMenuItems.swift, core/Sources/FileawayCore/Views/Viewer/LocationRow.swift, core/Sources/FileawayCore/Views/Viewer/LocationSection.swift, core/Sources/FileawayCore/Views/Viewer/Sidebar.swift, ios/Fileaway/FileawayApp.swift, ios/Fileaway/Views/Wizard/RulePicker.swift, ios/Fileaway/Views/Wizard/RulePickerRow.swift, ios/Fileaway/Views/Wizard/WizardView.swift, macos/Fileaway/FileawayApp.swift, macos/Fileaway/Scenes/Wizard.swift, macos/Fileaway/Toolbars/SelectionToolbar.swift, macos/Fileaway/Views/Settings/GeneralSettingsView.swift, macos/Fileaway/Views/Wizard/WizardView.swift
This change also includes a drive-by fix to a bug which led to duplicate `ApplicationModel` instances, causing unnecessary directory indexing.
=> fix: Refresh iOS folders when foregrounding the app

core/Sources/FileawayCore/Model/RuleFormModel.swift, core/Sources/FileawayCore/Model/RuleModel.swift, core/Sources/FileawayCore/Model/RulePickerModel.swift, core/Sources/FileawayCore/Model/RulesModel.swift, core/Tests/FileawayCoreTests/RulesModelTests.swift, ios/Fileaway/Views/Wizard/RulePickerRow.swift, macos/Fileaway/Views/Settings/ComponentView.swift, macos/Fileaway/Views/Wizard/RulePickerRow.swift
This change makes the URL names more explicit in an attempt to avoid confusion between the URL of the archive, and the URL of the rules file within the archive.
=> refactor: Clean up the URL naming

core/Sources/FileawayCore/Configuration/VariableModel.swift, core/Sources/FileawayCore/Model/RuleModel.swift, core/Sources/FileawayCore/Model/RulesModel.swift, core/Tests/FileawayCoreTests/Extensions/XCTestCase.swift, core/Tests/FileawayCoreTests/RuleModelTests.swift, core/Tests/FileawayCoreTests/RulesModelTests.swift, ios/Fileaway/Views/Editor/RuleView.swift, macos/Fileaway/Views/Settings/VariablesTable.swift
The iOS app has modal rule editing which takes a copy of the rule models on edit, only updating the rule set on save. Unfortunately, we weren't performing a full deep copy of the rule model, meaning that changes were being applied and written to disk, even on cancel.
=> fix: Rules variable are incorrectly updated after cancelling edit on iOS

core/Sources/FileawayCore/Extensions/FileManager.swift, core/Sources/FileawayCore/Extensions/Set.swift, core/Sources/FileawayCore/Model/DirectoryViewModel.swift, core/Sources/FileawayCore/Utilities/DirectoryMonitor.swift, core/Sources/FileawayCore/Utilities/FileInfo.swift, core/Sources/FileawayCore/Views/Viewer/DirectoryView.swift, core/Tests/FileawayCoreTests/DirectoryMonitorTests.swift, core/Tests/FileawayCoreTests/DirectoryViewModelTests.swift, core/Tests/FileawayCoreTests/Extensions/FileManager.swift, core/Tests/FileawayCoreTests/Extensions/Set.swift, core/Tests/FileawayCoreTests/Extensions/XCTestCase.swift, core/Tests/FileawayCoreTests/SetTests.swift, core/Tests/FileawayCoreTests/URLTests.swift
Ensure `DirectoryMonitor` correctly indexes newly-added folders, and deletes files contained within removed folders. As part of this fix, the change introduces unit tests for `DirectoryMonitor` and `DirectoryViewModel`.
This includes a drive-by fix for selection management when viewing documents using QuickLook: unfortunately it seems like there's a bug with the SwiftUI QuickLook bindings on iOS that means the current item binding isn't updated when paging through items in the QuickLook view. Given this, it's not possible to ensure the selection is correct, so we simply allow the selection to be cleared when the item binding goes nil (indicating that the QuickLook view has been dismissed).
=> fix: Directory views don't notice changes when moving or deleting folders

core/Tests/FileawayCoreTests/DirectoryMonitorTests.swift, core/Tests/FileawayCoreTests/DirectoryViewModelTests.swift
These tests have unfortunately always been brittle and it’s likely they’re failing due to race conditions or concurrency changes and not necessarily represent issues in the main functionality. This change disables them until the problem can be investigated more thoroughly or the file monitoring can be replaced with something more robust (e.g., the approach in Folders).
=> test: Disable failing lifecycle tests

ios/Fileaway-iOS.xcodeproj/project.pbxproj
This will hopefully reduce the amount of project file churn in the future.
=> refactor: Convert the iOS Xcode project to folders

macos/Fileaway/Scenes/Wizard.swift, macos/Fileaway/Views/Wizard/WizardView.swift
=> refactor: Rename the mac wizard view back to `WizardView`

apple/Fileaway/Views/Viewer/DirectoryView.swift, apple/Fileaway/Views/Viewer/EmptyDirectoryPlaceholderView.swift
Fixes #632.
before
after
(we could also remove the button)
=> fix: 🔎 Make empty search results clearer
